### ISSUE TITLE
Unable to parse ?

### ISSUE THREAD

**Issue by Paradoxu** [agilord/cron#12]
I'm trying to schedule a job that runs every weekday at 7:00, and this is the corn string I'm using: 0 0 7 ? * MON-FRI *  which should work but I get an error when scheduling, example:

```
final cronString = '0 0 7 ? * MON-FRI *';
final cron = Cron();
cron.schedule(Schedule.parse(cronString), () async {
   // do something
});
```

When I run the above code this is the error:
```
Exception: Unable to parse: ?
#0      parseConstraint (package:cron/src/constraint_parser.dart:36:3)
#1      new Schedule (package:cron/cron.dart:76:9)
#2      new Schedule.parse (package:cron/cron.dart:96:12)
#3      main (package:dart_oil_job_sync/main.dart:13:26)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Should I use some other syntax? Is there an example?

**Comment by isoos** [comment]
`?` or `mon-fri` is not yet supported. PRs are welcome :)

**Comment by Paradoxu** [comment]
> `?` or `mon-fri` is not yet supported. PRs are welcome :)

I'm gonna work on that PR :)
